### ISSUE TITLE
[TODO] 오늘 해야할 작업

### ISSUE THREAD

**Issue by SHcommit** [IF-TG/iOS#45]
## Todo

- [ ] 공지사항 알림창 UI 개발
- [ ] 공지사항 알림 서버 연동
- [ ] 알림창 팝업 애니메이션 적용

## Knowledge

- CALayer
- 애니메이션 도중 알림창 닫는 상황 처리 방법
...

## Etc
